apiVersion: v1
kind: Secret
metadata:
  name: client-appname-api-secret             
type: Opaque
data:
  secret_key: 
  database_url: 
  build_with_geo_libraries: 
  disable_collectstatic: 
  debug: 
  aws_storage_bucket_name: 
  aws_secret_access_key: 
  aws_s3_region_name: 
  aws_s3_endpoint_url: 
  aws_access_key_id: 
  twilio_id: 
  twilio_key: 
  celery_broker_url: 
  celery_result_backend: 
  one_signal_app_id: 
  one_singal_app_key: 
  sendgrid_api_key: 